### ISSUE TITLE
Dates pre-1970 epoch result in OverflowError

### ISSUE THREAD

**Issue by walkerdb** [KoffeinFlummi/Chronyk#7]
On windows machines, any date entered that is prior to the Jan 1 1970 epoch date results in the following error:

```
OverflowError: mktime argument out of range
```
The operation throwing the error is:
```
timestamp = time.mktime(struct)
```
Seems to be a limitation of the built in mktime function that only applies to Windows machines -- see [here](http://stackoverflow.com/questions/2518706/python-mktime-overflow-error).

**Comment by KoffeinFlummi** [comment]
Sorry for getting back to you so late, but 5da4f352e9b3e3fe272c5dfbfa3fc2c06be09c19 should fix this. I have not been able to test this on Windows myself though.

**Comment by walkerdb** [comment]
Thanks for working on it!

The new fix does seem like the right direction. It now gives a new OverflowError, this time with the dt.timestamp() function on line 21:

    OverflowError: timestamp out of range

**Comment by KoffeinFlummi** [comment]
Oh goodie. I guess that's what I get for trusting datetime. How about now:  1216d3ce5a5ee7e0c5927f0f144fad98e8c23952?

**Comment by walkerdb** [comment]
Progress!

New error:

    Traceback (most recent call last):
    File "<input>", line 1, in <module>
    File "C:\Python34\lib\site-packages\chronyk\chronyk.py", line 138, in __repr__
        return "Chronyk({})".format(self.timestring())
    File "C:\Python34\lib\site-packages\chronyk\chronyk.py", line 495, in timestring
        return time.strftime(pattern, time.gmtime(timestamp))
    OSError: [Errno 22] Invalid argument

**Comment by KoffeinFlummi** [comment]
After finally spinning up a Windows VM and a few more dumb workarounds, this should be working now. Let me know if you're still having issues.

**Comment by walkerdb** [comment]
Wow, what a mess. Windows is the worst.

Thanks for taking the time to make the fix. I'll give it a try later tonight.

**Comment by walkerdb** [comment]
Just got around to spinning it up again, and it works! Would it be worth upping the pypi version number?

**Comment by KoffeinFlummi** [comment]
> Just got around to spinning it up again, and it works! Would it be worth upping the pypi version number?

Done: https://pypi.python.org/pypi?:action=display&name=Chronyk
